--- #YAML:1.0
name:               IPTables-Log
version:            0.0003
abstract:           Parse iptables/netfilter syslog messages.
author:
    - Andy Smith <ams@meh.org.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::GUID:   0.045
    NetAddr::IP:  4.027
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
